version: '3.8'

services:
  postgres_dev:
    image: postgres:16
    container_name: postgres_dev
    environment:
      POSTGRES_USER: mainfix
      POSTGRES_PASSWORD: mainfix
      POSTGRES_DB: mainfix
    ports:
      - '5432:5432'
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U mainfix -d mainfix']
      interval: 2s
      timeout: 2s
      retries: 20
    restart: unless-stopped

  postgres_test:
    image: postgres:16
    container_name: postgres_test
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: mainfix_test
    ports:
      - '5433:5432' # Ã©vite le conflit avec le dev
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test_user -d mainfix_test']
      interval: 2s
      timeout: 2s
      retries: 20
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis_local
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  pgdata_dev:
  pgdata_test:
  redis_data:
